name: 'Ping URL Action'
description: 'Custom action to ping a URL'
inputs:
  url:
    description: 'The URL to ping'
    required: true
    default: 'https://example.com'  # Default URL
    # Specify choices in the description for user clarity, but not as options
  max_trials:
    description: 'Maximum trials until action fails'
    required: false
    default: '10'  # Default value if not provided
  delay:
    description: 'Delay in seconds between trials'
    required: false
    default: '5'  # Default value if not provided
runs:
  using: 'docker'
  image: 'Dockerfile'
