# .github/actions/docker-ping-url/action.yml

name: "Ping URL"
description: "Pings a URL for a specified number of trials with a delay between each"
inputs:
  url:
    description: "URL to ping"
    required: true
  max_trials:
    description: "Maximum number of ping trials"
    required: true
    default: 5
  delay:
    description: "Delay in seconds between each ping"
    required: true
    default: 1
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.url }}
    - ${{ inputs.max_trials }}
    - ${{ inputs.delay }}
