FROM python:alpine3.19

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the requirements file and install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the code
COPY main.py ./

# Command to run the script
CMD ["python", "./main.py"]
