# Use a lightweight Python image
FROM python:alpine3.19

# Set the working directory
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy the Python script
COPY main.py .

# Define the default command
CMD ["python", "main.py"]
