name: Cache Node and NPM Dependencies
description: This action allows caching of both Node and NPM dependencies based on the package-lock.json file.

inputs:
  node-version:
    description: NodeJS version to use
    required: true
    default: '20.x'
  working-dir:
    description: The working directory of the application
    required: false
    default: '.'
  target-env:
    description: "Environment type: 'dev' or 'prod'. Controls whether dev dependencies are installed."
    required: false
    default: dev

runs:
  using: composite
  steps:
    - name: Setup NodeJS version ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: ${{ inputs.working-dir }}/node_modules
        key: ${{ runner.os }}-node-modules-${{ inputs.node-version }}-${{ inputs.target-env }}-${{ hashFiles(inputs.working-dir + '/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-${{ inputs.node-version }}-

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        if [ "${{ inputs.target-env }}" == "prod" ]; then
          npm ci --omit=dev
        else
          npm ci
        fi
      shell: bash
      working-directory: ${{ inputs.working-dir }}
