name: 02 - Workflow Events

on:
  push:
    branches:
      - main  # Adjust if your default branch is different
  pull_request:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - name: Show the trigger
        run: | 
            echo "The workflow was triggered by: ${{ github.event_name }}"
