name: 12 - Working with Outputs

on:
  workflow_dispatch:
    inputs:
      build-status:
        type: choice
        description: 'Choose build status'
        options:
          - success
          - failure
        default: success

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build.outputs.status }}
      output1: ${{ steps.build.outputs.output1 }}
    steps:
      - name: Print GITHUB_OUTPUT path
        run: 'echo "GITHUB_OUTPUT path: ${GITHUB_OUTPUT}"'
        
      - name: Build
        id: build
        run: |
          echo "status=${{ github.event.inputs.build-status }}" >> "$GITHUB_OUTPUT"
          echo "output1=value1" >> "$GITHUB_OUTPUT"
          echo "output2=value2" >> "$GITHUB_OUTPUT"
          echo "Contents of GITHUB_OUTPUT after initial values:"
          cat "$GITHUB_OUTPUT"
        
      # Intentionally overwrite the GITHUB_OUTPUT content
      - name: Step with mistake
        run: |
          echo "mistake=true" > "$GITHUB_OUTPUT"
          echo "Contents of GITHUB_OUTPUT after overwrite:"
          cat "$GITHUB_OUTPUT"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: needs.build.outputs.build-status == 'success'
    steps:
      - name: Deploy
        run: echo "Deploying"
      
      - name: Print Outputs
        run: 'echo "Value of output1 from build job: ${{ needs.build.outputs.output1 }}"'
