name: 12 - Working with Outputs

on:
  workflow_dispatch:
    inputs:
      build-status:
        type: choice
        options:
          - success
          - failure
        default: success
        description: "Set the build status for controlling deployment."

jobs:
  # Job 1: Build
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build.outputs.status }} # Output for downstream jobs
    steps:
      - name: Print GITHUB_OUTPUT path
        run: 'echo "GITHUB_OUTPUT path: ${GITHUB_OUTPUT}"'


      - name: Build
        id: build
        run: echo "status=${{ github.event.inputs['build-status'] }}" >> $GITHUB_OUTPUT

  # Job 2: Deploy
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.outputs.build-status == 'success' }}
    steps:
      - name: Deploy
        run: echo "Deploying"
