name: 15 - Working with Matrices

on:
  workflow_dispatch:

jobs:
  backwards-compatibility:
    runs-on: ubuntu-latest
    # Previous backwards-compatibility job configuration...

  include-example:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          color: [red, green]
          shape: [circle, square]
          size: [small, large]
          include:
            - opacity: 50
            - color: red
              opacity: 75
            - shape: circle
              opacity: 100
            - color: red
              shape: triangle
    name: ${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}-${{ matrix.opacity || '' }}
    steps:
        - name: Dummy step
          run: echo "${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}-${{ matrix.opacity || '' }}"
  