# .github/workflows/19-1-concurrency.yaml

name: 19 - 1 - Managing Concurrency

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Ping URL
        uses: ./.github/actions/docker-ping-url
        with:
          url: "https://example.invalid"  # Valid but unreachable URL
          max_trials: 20
          delay: 5
