name: 20 - Workflow Security

on: pull_request

jobs: 
    unsafe-pr:
        runs-on: ubuntu-latest
        steps: 
            - name: checkout code
              uses: actions/checkout@v3

            - name: check PR title
              run: |
                  title=${{ github.event.pull_request.title }}
                  if [[ $title =~ ^feat ]]; then
                  echo "PR is a feature"
                  exit 0
                  else
                  echo "PR is not a feature"
                  exit 1
                  fi
    safe-pr:
        runs-on: ubuntu-latest
        steps: 
            - name: checkout code
              uses: actions/checkout@v3
             
            - name: check PR title
              env: 
                TITLE: ${{ github.event.pull_request.title }}
              run: |
                  if [[ TITLE =~ ^feat ]]; then
                  echo "PR is a feature"
                  exit 0
                  else
                  echo "PR is not a feature"
                  exit 1
                  fi
    js-safe-pr:
        runs-on: ubuntu-latest
        steps: 
            - name: checkout code
              uses: actions/checkout@v3
                         
            - name: check PR title
              uses: ./.github/actions/security-safe-input
              with: 
                pr-title: ${{ github.event.pull_request.title }}
              